const banned: string[] = [
  "about",
  "button",
  "can be found here",
  "click",
  "click here",
  "continue",
  "continue reading",
  "details",
  "email",
  "figure",
  "found here",
  "here",
  "learn more",
  "link",
  "more",
  "more details",
  "more here",
  "online",
  "read more",
  "resource",
  "the article",
  "the document",
  "the entry",
  "the link",
  "the page",
  "the post",
  "the site",
  "the website",
  "this article",
  "this document",
  "this entry",
  "this link",
  "this page",
  "this post",
  "this site",
  "this website",
  "url",
  "website",
];

export default banned;
